### PR TITLE
Refactors to BEM and cleans up some markup

### PR DESCRIPTION
**Pull request by rauhryan**
Relates to #358 

I jumped into the comments on #358 and wanted to help out. 

I started off by finding a [rough closed div tag](https://github.com/huboard/huboard-web/blob/591292cf52d8f74f0c04ddab7b120d0dad1b2605/app/views/board/create_board.html.erb#L44) inside the form tags and started backtracking and folding up all the markup to find out how to fix it. I then needed to add indenting so I'm very sorry for the diff not being very useful. 

Things I have address in the PR 

  - [Fixes href quoting problem](https://github.com/huboard/huboard-web/pull/358#discussion-diff-74652033)
  - [Check if the repo owner is an organization](https://github.com/huboard/huboard-web/pull/358#discussion_r74652878)
  - [Adds analytic paths to determine retrys or abandons](https://github.com/huboard/huboard-web/pull/358#discussion_r74652243)

### CODE REVIEW

**Comment by discorick** [comment]
I am curious if you have a GA goal workflow in mind for abandons, we can infer them currently by any traffic that doesn't meet the goal requirements. Having said that 👍  for more data :D

**Comment by discorick** [comment]
Not a fan of the big purple buttons ? 
image

image

**Comment by rauhryan** [comment]
Idk based on the current implementation

you'd see 

  - /board/create => /board/creating
  - /board/create => /board/creating/abandon
  - /board/create => /board/creating => /board/creating/retry
  - /board/create => /board/creating => /board/creating/abandon

Or some infinity combination of /creating => (retry...abandon)

**Comment by rauhryan** [comment]
> Not a fan of the big purple buttons ? 

It wasn't the design that threw me off, I actually prefered the bigger purple buttons. 

The css debt didn't seem worth it, there was a triple specific selector on a 'input.btn.primary' nested under another class 

There was also use of forms and form inputs inside anchor tags. They didn't really need to be forms and serve just fine as anchor tags that are styled.

I got carried away fixing the markup that I just simplified it all to use the built in bootstrap styles.

**Comment by discorick** [comment]
> It wasn't the design that threw me off, I actually prefered the bigger purple buttons.

> The css debt didn't seem worth it, there was a triple specific selector on a 'input.btn.primary' nested under another class

Not sure I 100% follow - if we prefer a certain styling, why can't we achieve without the debt ? Aren't we optimizing in the opposite direction of where we want to go then?

**Pull request merged**
