### PR TITLE
Added 'assign yourself' link

### PR DESCRIPTION
**Pull request by kevPo**
Added ability to assign yourself without having to click on the assignee fly-out.

### CODE REVIEW

**Comment by discorick** [comment]
Looks good to me, thanks @kevPo !

@rauhryan :shipit: ?
image

**Comment by rauhryan** [comment]
Looks pretty good to me

thanks @kevPo 

:shipit:

**Comment by rauhryan** [comment]
Shipped and live for the world to see! thanks @kevPo

**Comment by kevPo** [comment]
Glad to do it @rauhryan!  Thanks for providing such an awesome service :+1:

**Pull request merged**
