### PR TITLE
Ensures published event channels are lowercased

### PR DESCRIPTION
**Pull request by discorick**
Fixes sockets sometimes subscribing to a channel but never receiving any messages

### CODE REVIEW

**Comment by discorick** [comment]
Not ready for merge - theres still instances where sockets aren't kicking in

**Comment by discorick** [comment]
@rauhryan - this should probably be packaged with the next enterprise release

**Comment by rauhryan** [comment]
damn it, i thought i pushed this

**Comment by discorick** [comment]
@rauhryan You pushed a client-side only version of this PR, I realized after the fact channel names should be forced lowercase server-side also

**Pull request merged**
