### PR TITLE
Bumps ruby version up to latest supported heroku version

### PR DESCRIPTION
**Pull request by rauhryan**

### CODE REVIEW

**Comment by dahlbyk** [comment]
Any risk to this upgrade?

**Comment by rauhryan** [comment]
I'd say yes, but it's probably low. 

We are having memory issues on heroku, we can push this up and see if it improves in a few days

I'd like to upgrade puma as well, I did it for enterprise and haven't heard of any issues yet

**Comment by dahlbyk** [comment]
> I'd like to upgrade puma as well, I did it for enterprise and haven't heard of any issues yet

While you're in upgrade mode, you could hit #219 (security patches) and bump jQuery to 1.11.* (our Ember can't do 1.12.* yet).

**Comment by rauhryan** [comment]
K, will do.

**Comment by dahlbyk** [comment]
> bump jQuery to 1.11.*

Oh hey, so I thought I had seen the app using jQuery 1.9.1, but it's actually Marketing & Dashboard that are using 1.9.1. App is 1.11.3.

Ember 1.13.13 removes the jQuery version match(https://github.com/emberjs/ember.js/commit/8e8ff9ef1c7a1fb0a824b0611dbcbf1f97643800), so we should be able to unpin in the jQuery version to take advantage of improvements in 1.12.0.

**Comment by dahlbyk** [comment]
We should also bump Rails for SaaS, i.e. https://github.com/huboard/huboard-web/commit/8824c86ea19fc5c62931443d00f68a7060f29049

**Pull request merged**
