### PR TITLE
Add Vagrant .bashrc

### PR DESCRIPTION
**Pull request by dahlbyk**
My initial goal was an alias to simplify running the app (I picked `s` in honor of `rails s`, but am not attached to it).

As a means to that end, I introduced a `.bashrc` to be referenced from Vagrant. Should make iterating on that experience easier.

### CODE REVIEW

**Comment by discorick** [comment]
A more puppet-esq way to to accomplish this:

- Add `.bashrc` to `puppet/local_modules/bash/files`
- In the puppet manifest add the following:

```ruby
file { `/vagrant/.bashrc`:
  ensure => present,
  owner => 'vagrant',
  group =>   'vagrant'
  source => 'puppet://modules/bash/.bashrc`
} 
```

**Comment by dahlbyk** [comment]
If I'm reading that correctly, won't that replace `.bashrc` altogether? (I assume you mean `file { '/home/vagrant/.bashrc`: ... }`?)

There's already a `.bashrc` with stuff in it, so I've been trying not to overwrite that.

**Comment by discorick** [comment]
Yes you are right `file { '/home/vagrant/bashrc/: ...`

I would like to start putting together a source controlled `.bashrc` anyways, lets pick what we like from the image as well.

**Comment by dahlbyk** [comment]
I think I'm going to try a different approach.

**Pull request closed without merging**
