### PR TITLE
WIP: Remove use of warden and use omniauth-github in preparation for supporting GitLab

### PR DESCRIPTION
**Pull request by stanhu**
Relates to huboard/ghee#37.

### CODE REVIEW

**Comment by rauhryan** [comment]
Hmmm interesting 

I will have to dig into this a little bit more when I have time. 

I ran into some problems with warden, specifically warden-github and it boiled down to SSL issues

Also, I'm not sure how we are going to support GitLab right now. 

If HuBoard should be one app or if it's completely separate "builds" of HuBoard and we have something like gitlab.huboard.com and possible github.huboard.com and so one

That's actually pretty interesting, I kind of like that idea, huboard.com could move to static site that's kind of like a train switch to the different subdomains. 

Would love to hear some thoughts on that...

**Comment by rauhryan** [comment]
@stanhu I am actively looking into this right now.

Proper OAuth flow is way more complex than I thought. 

Just want to let you know that we didn't forget about you. 

Let me know if you have some free time to skype or chat about how we want to move forward with this PR

Cheers, 

 - Ryan

**Comment by stanhu** [comment]
@rauhryan Somehow I missed this. Sure, maybe we can discuss this this week.

**Comment by dahlbyk** [comment]
Fortunately, some of the complexity to which @rauhryan was referring was due to a quirk in GitHub `public_repo`/`repo` behavior that seems to have been resolved (see https://github.com/huboard/huboard-web/issues/172#issuecomment-196328505).

Also FYI, https://github.com/huboard/huboard-web/pull/214 adds some OAuth complexity to support deploying review apps. We'll need to implement equivalent behavior with OmniAuth.

**Comment by discorick** [comment]
Closing as HuBoard for GitLab is no longer in development.

**Pull request closed without merging**
