### PR TITLE
Handles Ghee::Unauthorized exceptions

### PR DESCRIPTION
**Pull request by discorick**
Fixes bug where rails can lock a user out of huboard.com if their token is invalid but their csrf token is valid

### CODE REVIEW

**Comment by rauhryan** [comment]
@discorick excellent :) 

This saves us from throwing a 500.

What do you think about adding a redirect back to where they were when the error was thrown?

ie; 

 1. user is on ~/username/private_repo
 2. app throws Unauth
 3. user is redirect to ~/login
 4. **~/login redirects back to ~/username/private_repo** <- add this

**Comment by discorick** [comment]
The only danger I see with that kind of redirect is it assumes the user will always pick the same auth level at the login screen.

**Comment by rauhryan** [comment]
Let's do it, I'm pretty sure users have been asking for it for a long time

**Comment by discorick** [comment]
Ok, for the JSON responses it seems like the right thing to do. For HTML redirects I am not so sure.

**Comment by rauhryan** [comment]
Agreed, I think the json error is correct

**Pull request merged**
