### PR TITLE
Pinning closed issues

### PR DESCRIPTION
**Pull request by rauhryan**
When pulling issues, grab all closed issues (as opposed to only issues in the final column) and if they are not already in the final column, move them there. Add a modal confirmation when attempting to drag closed issues to the rest of the board (reopen on cancel)

Closes rauhryan/huboard#592 when merged
Closes rauhryan/huboard#258 when merged

### CODE REVIEW

**Comment by rauhryan** [comment]
:shipit:

**Comment by jakehow** [comment]
@rauhryan does this still preclude the workflow where you want > 1 column to be able to have closed issues?

For us that is a Staging column and a Production column. Merged PRs (read closed) should be viewable in either.

**Comment by rauhryan** [comment]
@jakehow right now we move all the closed issues to the final column. 

We haven't gotten to the ability to have closed in multiple columns yet. 

This is a huge improvement over the previous iteration that didn't show closed items if they weren't labeled for the final column. 

I'll review and keep an eye on waffleio/waffle.io#616 sounds like both tools are looking to solve the problem in a similar way. 

Thanks for the feedback

**Comment by jakehow** [comment]
@rauhryan got it, this should probably not close https://github.com/rauhryan/huboard/issues/258 in that case.  This issue still is a total block for our team (and it sounds like many others) from using this tool at all.

**Comment by rauhryan** [comment]
@jakehow have you considered using the open/closed as a sort of "virtual" column

> For us that is a Staging column and a Production column. Merged PRs (read closed) should be viewable in either.

We follow a similar workflow, we have a staging environment where we push up our pending PRs for review and QA

We allow open and closed issues in the final column so we treat, `final column and open` as a virtual column similar to your Staging, once the feature is live in production we close out the PR's and issues 

So for us, `final column and open` == "done" & `final column and closed` == "done, done"

**Comment by jakehow** [comment]
@rauhryan I think the issue revolves around the fact that our PRs are merged before they are in our last column unless I am misunderstanding your comment.

In order to get into our staging env a PR must be merged, it sounds like you may have a different setup.

**Comment by rauhryan** [comment]
Yeah, we don't merge into our default branch until we push to production. 

We deploy using git, we merge master into our PR branch and push that to the staging remote if all checks out we push it to the production remote *then* to the GitHub remote which triggers the `Merge` close of the PR and attached issues. 

It's a workflow we are experimenting with, it works really well for our team and we have plans to have HuBoard automate some things around that flow

You make a solid argument for multiple closed columns, we'll add it to the backlog

**Pull request merged**
