### PR TITLE
Creates a cached job to prevent event race conditions

### PR DESCRIPTION
**Pull request by discorick**
Alright, after much spiking and testing today - I think this should do the trick (I want to test it out further on the review app)

Unfortunately only production is fast enough to generate the race conditions, so we won't know for sure until we try there. 

@rauhryan @dahlbyk can you poke holes here?

fixes https://github.com/huboard/huboard/issues/608

### CODE REVIEW

**Comment by dahlbyk** [comment]
The seemingly consistent duplicate New Issue notifications are really due to a race condition?

**Comment by discorick** [comment]
It really feels that way, if two workers are handling the GH webhook, plus HB event simultaneously there is potential for the cache (which is non-blocking) to be too late while its setting `willPublish` 

I was _not_ actually able to repro duplicates on local or huboard-rails - only on cedar which is the only ENV with blazing fast dedicated workers.

**Comment by dahlbyk** [comment]
Code change looks solid. More room to DRY up the two base event jobs, but that can wait. Go ahead and :shipit: if you're satisfied with your testing.

**Comment by dahlbyk** [comment]
I'm still getting a double-tap on the demo app... Is that expected?

**Comment by discorick** [comment]
Yeah, huboard-rails is picking up GitHub webhook, and since dalli is a local cache, the review app has the cache key, not huboard-rails.

**Comment by rauhryan** [comment]
possibly randomize the delay time? still hacky but it might help.

Also... could we restrict the trouble makers to a special queue that isn't
parallel?

 - Ryan

**Comment by dahlbyk** [comment]
Switching the GH hook to also go through the review app resolved the double- tap. I think we're good!

**Pull request merged**
