### PR TITLE
Recomputes milestone filters on issue milestone change

### PR DESCRIPTION
**Pull request by discorick**
closes https://github.com/rauhryan/huboard/issues/547

### CODE REVIEW

**Comment by rauhryan** [comment]
Have you considered making the card recomputed its filters rather than the other way around?

Right now we got Filters -> [array of issues], maybe flip it to Issue -> [array of filters] if that makes sense 

Spider senses tell me that we are coupling filters to the "thing" being filtered

I feel like "soonish" we are going to add pulls as well as issues

I also have concerns about performance with large amounts of issues, here the filter functions would recomputed for *every* issue (I think)

**Comment by discorick** [comment]
Right now we have each individual card is computing its "visible", "dim", or "hidden" state based on each filters mode. So in a sense we already have cards all watching the same array of filters and computing itself depending on filter state. But its **really expensive** as each card runs through all the active conditions and **then** determines whether its hidden, if not its runs through them all again to check if its dim, and then settles on being visible.

All this to say I agree, performance for filters has no where to go but down in the current configuration.

**Comment by discorick** [comment]
Obviated by #110 . Closing.

**Comment by rauhryan** [comment]
:+1:

**Pull request closed without merging**
