### PR TITLE
Enable Optimizely in HuBoard SaaS

### PR DESCRIPTION
**Pull request by petey-rock**
Enable Optimizely in HuBoard SaaS

### CODE REVIEW

**Comment by dahlbyk** [comment]
We'll need to reference the partial in the other interesting views as well.

**Comment by dahlbyk** [comment]
The `OPTIMIZELY_KEY` config value didn't come over without adding it to `app.json`, but I'm OK with that - we usually don't need it. I've fixed for just this review app, and removed from the parent:

```
heroku config:set OPTIMIZELY_KEY=5531021703 -a huboard-rails-pr-263
heroku config:remove OPTIMIZELY_KEY -a huboard-rails
```

Optimizely request is coming through as expected:
firefox_2016-04-09_08-57-38

**Comment by dahlbyk** [comment]
It occurs to me that I may have merged this prematurely - I've restored the config value on huboard-rails if you want to test end-to-end in Optimizely before this hits production. (I'm pretty confident this will work just fine.)

**Comment by discorick** [comment]
Ill look at it today!

**Pull request merged**
