### PR TITLE
Moves private and public access buttons to the top

### PR DESCRIPTION
**Pull request by petey-rock**

### CODE REVIEW

**Comment by petey-rock** [comment]
screen shot 2016-04-26 at 10 46 06 am
 
Spacing look okay?

**Comment by dahlbyk** [comment]
I could use a bit more spacing, personally... Maybe 20px? @rauhryan, thoughts?

**Comment by petey-rock** [comment]
screen shot 2016-04-26 at 11 08 11 am
here's 24px

**Comment by dahlbyk** [comment]
What's the spacing above?

**Comment by petey-rock** [comment]
30px

**Comment by petey-rock** [comment]
screen shot 2016-04-26 at 11 08 11 am

heres 30px

**Comment by dahlbyk** [comment]
I like the symmetry. Push 30px?

**Comment by petey-rock** [comment]
cool!

**Comment by dahlbyk** [comment]
:sparkles:

**Comment by rauhryan** [comment]
👍

**Pull request merged**
