### PR TITLE
UX Branch for #177 Improved Login Flow

### PR DESCRIPTION
**Pull request by discorick**
Moving discussion and spikes for #177 UX to this PR

### CODE REVIEW

**Comment by discorick** [comment]
Simple Dashboard with Private hidden on Public only Auth:

image

**Comment by discorick** [comment]
@rauhryan heres an example of what we talked about this morning:
image

**Comment by dahlbyk** [comment]
What if the "Looking for private repositories?" message were moved up to alert bar, e.g. instead of "Only public repositories are currently visible!" we showed:

> Looking for private reposorities? [Click here to allow private access.](#)

**Comment by dahlbyk** [comment]
In fact, you could add a bit of clever CSS to have that block effectively "point" up to a disabled Private tab.

firefox_2016-01-28_11-02-20

Should be something like this...
```css
.public-only-hero:before {
  content: '';
  width: 0px; height: 0px;
  margin: -20px 25px 0px auto;
  border-bottom: 15px solid rgb(251, 238, 213);
  border-left: 15px solid transparent;
  border-right: 15px solid transparent;
}
```

**Comment by discorick** [comment]
@dahlbyk So remove the left-hand button / alert altogether is what you are proposing ?

**Comment by dahlbyk** [comment]
> So remove the left-hand button / alert altogether is what you are proposing ?

Yeah. Takes up the same amount of vertical space as the current alert, without the extra UI component on the left that otherwise doesn't really seem to fit. Just my $.02.

Not sure the asterisk on Private is helpful, since we don't indicate anywhere what the asterisk means.

**Comment by discorick** [comment]
Asterisk is _supposed_ to indicate theres a hover over effect, it seems like its not really working. 

I actually kind of like the greyed out private tab, what do you think @rauhryan ?

**Comment by discorick** [comment]
Closes in deference to #285

**Pull request closed without merging**
