### PR TITLE
Adds word-break: break-all; to card titles in order to prevent columns from growing beyond the limit

### PR DESCRIPTION
**Pull request by rauhryan**
related to huboard/huboard#631

### CODE REVIEW

**Comment by discorick** [comment]
:shipit:

**Comment by dahlbyk** [comment]
This was a step backward - all words wrap wherever now, not just words that are too long to fit.

**Comment by seanlinsley** [comment]
I'd have to agree, it's much harder to read ticket titles now.

**Comment by rauhryan** [comment]
huboard_huboard_huboard

**Comment by seanlinsley** [comment]
:+1:

**Pull request merged**
