### PR TITLE
hides adjacently hidden cards but leaves a little sliver for filtered ones

### PR DESCRIPTION
**Pull request by rauhryan**
So this was just a fun one, what do you think?

Not filtered...

rauhryan_skipping_stones_repo_huboard

Filtered...

rauhryan_skipping_stones_repo_huboard

### CODE REVIEW

**Comment by discorick** [comment]
Personally I like hiding cards 100% only because busy boards tend to have slivers pushing visible cards out of view. Maybe we could "bunch up" slivers together? I think that could possibly look awesome

**Comment by rauhryan** [comment]
Yep thats what it does :) 

It bunches them together, so 

this... 

rauhryan_skipping_stones_repo_huboard
vs...
rauhryan_skipping_stones_repo_huboard

**Comment by discorick** [comment]
Wellllllll in that case :thumbsup:

**Comment by emadrid** [comment]
noice!

**Pull request merged**
