### PR TITLE
Card redesign layout

### PR DESCRIPTION
**Pull request by discorick**
Pathway to 🚢 
  - [x] Task card layouts
  - [x] Issue Blocked/Ready labels as states
  - [x] Milestone card layouts
  - [x] Issue Reference UX
     - [x] also https://github.com/huboard/huboard-web/pull/338#issuecomment-237854443
  - [x] Scrolling task columns
  - [x] Acceptable Clientside Perf

closes: https://github.com/huboard/huboard/issues/261
closes: https://github.com/huboard/huboard-web/issues/318
closes: https://github.com/huboard/huboard/issues/372

### CODE REVIEW

**Comment by discorick** [comment]
@rauhryan @dahlbyk, Making good progress on this but there are still some items remaining before 🚢 

- [ ] Blocked/Ready states, should have those done shortly
- [ ] Full label lists on hover (currently excess labels are hidden based on card width)
- [ ] Assignee Expansion, I have limited visible avatars to 3 for performance reasons
- [ ] BUG: Assignee popover hides behind adjacent cards
- [ ] UX: Long repository names can bleed into the assignee avatars

@rauhryan additionally do you have png's for the state trays? I.E: the styled purple checkmark: 
image

**Comment by dahlbyk** [comment]
For the record, I have confirmed https://github.com/huboard/huboard-web/issues/318 is fixed using https://huboard-rails-pr-327.herokuapp.com/huboard-testing/spooky-octo-pug#/milestones/issues/155627505:
firefox_2016-08-03_11-50-12

**Comment by discorick** [comment]
Just noticed this: 
image

@rauhryan z-index doesn't seem to help, ideas on how I can bring the labels overtop the issue below?

**Comment by rauhryan** [comment]
Nope, there is no good way to do it. 

Wouldn't consider it blocking, the only way to fix it is to absolutely position a div on the body or something

**Comment by discorick** [comment]
@rauhryan I ran into a little trouble with: https://github.com/huboard/huboard-web/pull/327/commits/ce6107e8cc3305e67713e21e489b9614d8c3bdbf

On Firefox:
  - Visit rauhryan/skipping_stones_repo
  - scroll the first column until it loads more issues
  - watch the issues in the column to the left, they resize

**Comment by discorick** [comment]
> Nope, there is no good way to do it.

> Wouldn't consider it blocking, the only way to fix it is to absolutely position a div on the body or something

Ok no worries, I wouldn't consider it blocking either

**Comment by rauhryan** [comment]
> Visit rauhryan/skipping_stones_repo
> scroll the first column until it loads more issues
> watch the issues in the column to the left, they resize

I'm not seeing what you mean

**Comment by discorick** [comment]
@rauhryan can you revert https://github.com/huboard/huboard-web/pull/327/commits/e7bffb258fb8c4eaa03b88bbe30dfd29ecd07d5f ? This has already been addressed in the references branch

**Pull request merged**
