### PR TITLE
Upgrades HuBoard to ember 1.13

### PR DESCRIPTION
**Pull request by rauhryan**
BooYah!

### Notable Changes:

- Complete teardown and rewrite of the columns/board code to fix serious card related bugs (cards and columns disappearing, not creating, or double creating)
- Incoming Socket Events should behave far more reliably 
- Improved rending speeds for boards

### CODE REVIEW

**Comment by discorick** [comment]
Woop Woop!

**Comment by rauhryan** [comment]
:shipit:   ???

**Comment by discorick** [comment]
How about :shipit: tomorrow ? Want to look over the settings object.

**Comment by rauhryan** [comment]
:shipit:

**Pull request merged**
